/**
 * Auto-generated by scripts/chill-generate-animate.mjs from Chill Component (MIT).
 * @see https://gitlab.com/side_project/chill-component
 */
import anime from "animejs";
import { pipe } from "remeda";
import { getKeyframeList } from "./chill-cat-face-utils";


export async function runChillEyebrowAnimation(
  svgId: string,
  facialExpression: string,
): Promise<void> {
  const partIdList = ["eyebrow-r","eyebrow-l"] as const;
  function getTargetId(svgId: string, partId: string) {
    return `#${svgId} #face-eyebrow #${partId}`;
  }
  const facialExpressionProviderMap: Record<string, () => Promise<void>> = {
  neutral: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'neutral')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  excited: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'excited')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  happy: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'happy')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          keyframes: pipe(
            keyframeList.map((keyframe) => keyframe[partId]),
            /** 頭尾相接
             *
             * 因為使用 direction: 'alternate' 效果不自然
             */
            (list) => {
              const newList = [...list].reverse().slice(1)
              return [...list, ...newList]
            },
          ),
          duration: 1800,
          loop: true,
        }).finished,
      ),
    )
  },
  sad: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'sad')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  angry: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'angry')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  surprised: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'surprised')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  derpy: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'derpy')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  speechless: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'speechless')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  pleasant: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'pleasant')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  confidence: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'confidence')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
};
  anime.remove(partIdList.map((p) => getTargetId(svgId, p)));
  await facialExpressionProviderMap[facialExpression]?.();
}

export async function runChillMouthAnimation(
  svgId: string,
  facialExpression: string,
): Promise<void> {
  const partIdList = ["palate","jaw"] as const;
  function getTargetId(svgId: string, partId: string) {
    return `#${svgId} #face-mouth #${partId}`;
  }
  const facialExpressionProviderMap: Record<string, () => Promise<void>> = {
  neutral: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'neutral')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  excited: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'excited')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          keyframes: keyframeList.map((keyframe) => keyframe[partId]),
          duration: 600,
          delay: 400,
          loop: true,
          easing: 'easeInOutCirc',
          direction: 'alternate',
        }).finished,
      ),
    )
  },
  happy: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'happy')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          keyframes: keyframeList.map((keyframe) => keyframe[partId]),
          duration: 600,
          delay: 400,
          loop: true,
          easing: 'easeInOutCirc',
          direction: 'alternate',
        }).finished,
      ),
    )
  },
  sad: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'sad')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          keyframes: keyframeList.map((keyframe) => keyframe[partId]),
          duration: 600,
          delay: 400,
          loop: true,
          easing: 'easeInOutCirc',
          direction: 'alternate',
        }).finished,
      ),
    )
  },
  angry: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'angry')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  surprised: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'surprised')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          keyframes: keyframeList.map((keyframe) => keyframe[partId]),
          duration: 600,
          delay: 400,
          loop: true,
          easing: 'easeInOutCirc',
          direction: 'alternate',
        }).finished,
      ),
    )
  },
  derpy: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'derpy')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  speechless: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'speechless')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  pleasant: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'pleasant')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
  confidence: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'confidence')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )
  },
};
  anime.remove(partIdList.map((p) => getTargetId(svgId, p)));
  await facialExpressionProviderMap[facialExpression]?.();
}

export async function runChillEyeAnimation(
  svgId: string,
  facialExpression: string,
): Promise<void> {
  const partIdList = ["eye-r", "eye-l"] as const;
  function getTargetId(svgId: string, partId: string) {
    return `#${svgId} #face-eye #${partId}`;
  }
  const facialExpressionProviderMap: Record<string, () => Promise<void>> = {
  neutral: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'neutral')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          keyframes: keyframeList.map((keyframe) => keyframe[partId]),
          duration: 50,
          delay: 3000,
          loop: true,
          direction: 'alternate',
        }).finished,
      ),
    )
  },
  excited: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'excited')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          keyframes: pipe(
            keyframeList.map((keyframe) => keyframe[partId]),
            /** 頭尾相接
             *
             * 因為使用 direction: 'alternate' 效果不自然
             */
            (list) => {
              const newList = [...list].reverse().slice(1)
              return [...list, ...newList]
            },
          ),
          duration: 1600,
          loop: true,
        }).finished,
      ),
    )
  },
  happy: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'happy')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          keyframes: pipe(
            keyframeList.map((keyframe) => keyframe[partId]),
            /** 頭尾相接
             *
             * 因為使用 direction: 'alternate' 效果不自然
             */
            (list) => {
              const newList = [...list].reverse().slice(1)
              return [...list, ...newList]
            },
          ),
          duration: 1600,
          loop: true,
        }).finished,
      ),
    )
  },
  sad: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'sad')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          keyframes: pipe(
            keyframeList.map((keyframe) => keyframe[partId]),
            /** 頭尾相接
             *
             * 因為使用 direction: 'alternate' 效果不自然
             */
            (list) => {
              const newList = [...list].reverse().slice(1)
              return [...list, ...newList]
            },
          ),
          duration: 1600,
          easing: 'easeInOutCubic',
          loop: true,
        }).finished,
      ),
    )
  },
  angry: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'angry')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 200,
          easing: 'easeInOutCirc',
        }).finished,
      ),
    )
  },
  surprised: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'surprised')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 500,
        }).finished,
      ),
    )

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          keyframes: pipe(
            keyframeList.map((keyframe) => keyframe[partId]),
            /** 頭尾相接
             *
             * 因為使用 direction: 'alternate' 效果不自然
             */
            (list) => {
              const newList = [...list].reverse().slice(1)
              return [...list, ...newList]
            },
          ),
          duration: 1400,
          delay: 400,
          loop: true,
        }).finished,
      ),
    )
  },
  derpy: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'derpy')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 800,
        }).finished,
      ),
    )
  },
  speechless: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'speechless')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 800,
        }).finished,
      ),
    )
  },
  pleasant: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'pleasant')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          duration: 800,
        }).finished,
      ),
    )
  },
  confidence: async () => {
    const keyframeList = getKeyframeList(svgId, partIdList, 'confidence')

    await Promise.all(
      partIdList.map((partId) =>
        anime({
          targets: getTargetId(svgId, partId),
          ...keyframeList[0]?.[partId],
          easing: 'easeInOutCirc',
          duration: 800,
        }).finished,
      ),
    )
  },
};
  anime.remove(partIdList.map((p) => getTargetId(svgId, p)));
  await facialExpressionProviderMap[facialExpression]?.();
}
